spring:
  datasource:    
    url: "jdbc:mysql://localhost:3307/test"
    username: root
    password: root
#    hikari:
#      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true    
